name: build
# on:
#   pull_request:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
#   schedule:
#     - cron: '23 0 * * *'

on: push

jobs:
  build_and_test:
    name: free_fleet
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    with:
      # NOTE: Avoid adding comments in the package lines, this can break some of the called scripts in github actions
      packages: |
        free_fleet
        free_fleet_examples
        free_fleet_adapter
