coverage:
  precision: 2
  round: down
  range: "35...100"
  status:
    project:
      default:
        informational: true
    patch: off
fixes:
  - "ros_ws/src/*/free_fleet/free_fleet/::"
  - "ros_ws/src/*/free_fleet/free_fleet_adapter/::"
ignore:
  - "**/tests"
  - "**/setup.py"
  - "ros_ws/src/*/free_fleet/free_fleet_exmaples"
