module FreeFleetData
{
  module RobotMode_Constants
  {
    const unsigned long MODE_IDLE = 0;
    const unsigned long MODE_CHARGING = 1;
    const unsigned long MODE_MOVING = 2;
    const unsigned long MODE_PAUSED = 3;
    const unsigned long MODE_WAITING = 4;
    const unsigned long MODE_EMERGENCY = 5;
    const unsigned long MODE_GOING_HOME = 6;
    const unsigned long MODE_DOCKING = 7;
    const unsigned long MODE_REQUEST_ERROR = 8;
  };
  struct RobotMode
  {
    unsigned long mode;
  };
  struct Location
  {
    long sec;
    unsigned long nanosec;
    float x;
    float y;
    float yaw;
    string level_name;
  };
  struct RobotState
  {
    string name;
    string model;
    string task_id;
    RobotMode mode;
    float battery_percent;
    Location location;
    sequence<Location> path;
  };
  struct ModeParameter
  {
    string name;
    string value;
  };
  struct ModeRequest
  {
    string fleet_name;
    string robot_name;
    RobotMode mode;
    string task_id;
    sequence<ModeParameter> parameters;
  };
  struct PathRequest
  {
    string fleet_name;
    string robot_name;
    sequence<Location> path;
    string task_id;
  };
  struct DestinationRequest
  {
    string fleet_name;
    string robot_name;
    Location destination;
    string task_id;
  };
};
