version: "3"

services:
  minimal-nav2-bringup:
    image: minimal-nav2-bringup
    build:
      context: ../../../
      dockerfile: .github/docker/minimal-nav2-bringup/Dockerfile
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=42

  minimal-zenoh-bridge:
    image: minimal-zenoh-bridge
    build:
      context: ../../../
      dockerfile: .github/docker/minimal-zenoh-bridge/Dockerfile
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=42

  minimal-zenoh-router:
    image: eclipse/zenoh
    restart: unless-stopped
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - RUST_LOG=debug
