version: "3"

services:
  minimal-nav2:
    image: minimal-nav2
    build:
      context: ../../
      dockerfile: .github/minimal-nav2/Dockerfile
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=42

  minimal-zenoh-bridge:
    image: minimal-zenoh-bridge
    build:
      context: ../../
      dockerfile: .github/minimal-zenoh-bridge/Dockerfile
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=42

  minimal-zenoh:
    image: minimal-zenoh
    build:
      context: ../../
      dockerfile: .github/minimal-zenoh/Dockerfile
    network_mode: host
    stdin_open: true
    tty: true
