name: build-and-test

inputs:
  ros-distribution:
    description: string, ROS distribution to setup
    required: true
  zenoh-version:
    description: string, version of eclipse-zenoh to install from pip
    required: true
  nav1-integration-testing:
    description: string, supports ON or OFF only
    required: false
    default: "OFF"
  nav2-integration-testing:
    description: string, supports ON or OFF only
    required: false
    default: "OFF"

runs:
  using: composite
  steps:
    - name: install dependencies
      run: |
        sudo apt update && sudo apt install python3-pip ros-${{ inputs.ros-distribution }}-rmw-cyclonedds-cpp -y
        pip3 install eclipse-zenoh==${{ inputs.zenoh-version }} pycdr2 rosbags nudged --break-system-packages
      shell: bash

    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ inputs.ros-distribution }}

    - name: build
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: free_fleet free_fleet_adapter free_fleet_examples
        target-ros2-distro: ${{ inputs.ros-distribution }}
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                  "-DNAV1_INTEGRATION_TESTING=${{ inputs.nav1-integration-testing }}",
                  "-DNAV2_INTEGRATION_TESTING=${{ inputs.nav2-integration-testing }}"
              ],
              "mixin": ["coverage-pytest"]
            }
          }
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
        skip-tests: true

    - name: test
      env:
        RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
        ROS_DOMAIN_ID: 0
      run: |
        cd ros_ws/
        colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
        colcon mixin update default
        colcon test --packages-select free_fleet free_fleet_adapter free_fleet_examples --mixin coverage-pytest
      shell: bash
