module MiddlewareMessages
{
  struct Time
  {
    long sec;
    unsigned long nanosec;
  };  

  struct Location
  {
    string map_name;
    double x;
    double y;

    boolean yaw_available;
    double yaw;
  };

  struct Waypoint
  {
    unsigned long index;
    Location location;

    boolean wait_until_available;
    Time wait_until;     
  };

  module RobotMode_Constants
  {
    const unsigned long Idle = 0;
    const unsigned long Charging = 1;
    const unsigned long Moving = 2;
    const unsigned long Paused = 3;
    const unsigned long Waiting = 4;
    const unsigned long Emergency = 5;
    const unsigned long Docking = 6;
    const unsigned long Error = 7;
    const unsigned long Undefined = 9;
    const unsigned long Custom = 10;  
  };

  struct RobotMode
  {
    unsigned long mode;
    string info;
  };

  struct PauseRequest
  {
    string robot_name;
    unsigned long task_id;
  };

  struct ResumeRequest
  {
    string robot_name;
    unsigned long task_id;
  };

  struct DockRequest
  {
    string robot_name;
    unsigned long task_id;
    string dock_name;
  };

  struct NavigationRequest
  {
    string robot_name;
    unsigned long task_id;
    sequence<Waypoint> path;
  };

  struct RelocalizationRequest
  {
    string robot_name;
    unsigned long task_id;
    Location location;
    unsigned long last_visited_waypoint_index;
  };

  struct RobotState
  {
    Time time;
    string name;
    string model;

    boolean task_id_available;
    unsigned long task_id;

    RobotMode mode;
    double battery_percent;
    Location location;
    unsigned long path_target_index;
  };
};
