/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: MiddlewareMessages.h
  Source: MiddlewareMessages.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"

#ifndef _DDSL_MIDDLEWAREMESSAGES_H_
#define _DDSL_MIDDLEWAREMESSAGES_H_


#ifdef __cplusplus
extern "C" {
#endif


typedef struct MiddlewareMessages_Location
{
  int32_t sec;
  uint32_t nanosec;
  double x;
  double y;
  double yaw;
  char * level_name;
} MiddlewareMessages_Location;



typedef struct MiddlewareMessages_ModeParameter
{
  char * name;
  char * value;
} MiddlewareMessages_ModeParameter;


#define MiddlewareMessages_RobotMode_Constants_MODE_IDLE 0
#define MiddlewareMessages_RobotMode_Constants_MODE_CHARGING 1
#define MiddlewareMessages_RobotMode_Constants_MODE_MOVING 2
#define MiddlewareMessages_RobotMode_Constants_MODE_PAUSED 3
#define MiddlewareMessages_RobotMode_Constants_MODE_WAITING 4
#define MiddlewareMessages_RobotMode_Constants_MODE_EMERGENCY 5
#define MiddlewareMessages_RobotMode_Constants_MODE_GOING_HOME 6
#define MiddlewareMessages_RobotMode_Constants_MODE_DOCKING 7
#define MiddlewareMessages_RobotMode_Constants_MODE_REQUEST_ERROR 8
#define MiddlewareMessages_RobotMode_Constants_MODE_UNDEFINED 9
#define MiddlewareMessages_RobotMode_Constants_MODE_CUSTOM 10


typedef struct MiddlewareMessages_RobotMode
{
  uint32_t mode;
  char * info;
} MiddlewareMessages_RobotMode;


typedef struct MiddlewareMessages_ModeRequest_parameters_seq
{
  uint32_t _maximum;
  uint32_t _length;
  MiddlewareMessages_ModeParameter *_buffer;
  bool _release;
} MiddlewareMessages_ModeRequest_parameters_seq;

#define MiddlewareMessages_ModeRequest_parameters_seq__alloc() \
((MiddlewareMessages_ModeRequest_parameters_seq*) dds_alloc (sizeof (MiddlewareMessages_ModeRequest_parameters_seq)));

#define MiddlewareMessages_ModeRequest_parameters_seq_allocbuf(l) \
((MiddlewareMessages_ModeParameter *) dds_alloc ((l) * sizeof (MiddlewareMessages_ModeParameter)))


typedef struct MiddlewareMessages_ModeRequest
{
  char * robot_name;
  char * task_id;
  MiddlewareMessages_RobotMode mode;
  MiddlewareMessages_ModeRequest_parameters_seq parameters;
} MiddlewareMessages_ModeRequest;



typedef struct MiddlewareMessages_NavigationRequest
{
  char * robot_name;
  char * task_id;
  dds_sequence_t path;
} MiddlewareMessages_NavigationRequest;



typedef struct MiddlewareMessages_Robotstate
{
  char * name;
  char * model;
  char * task_id;
  MiddlewareMessages_RobotMode mode;
  double battery_percent;
  MiddlewareMessages_Location location;
  dds_sequence_t path;
} MiddlewareMessages_Robotstate;



typedef struct MiddlewareMessages_GraphRequest
{
  uint32_t version;
} MiddlewareMessages_GraphRequest;



typedef struct MiddlewareMessages_Waypoint
{
  char * map_name;
  double x;
  double y;
  bool is_holding_point;
  bool is_passthrough_point;
  bool is_parking_spot;
  uint32_t index;
  char * name;
} MiddlewareMessages_Waypoint;



typedef struct MiddlewareMessages_Lane
{
  uint32_t entry;
  uint32_t exit;
} MiddlewareMessages_Lane;


typedef struct MiddlewareMessages_Graph_waypoints_seq
{
  uint32_t _maximum;
  uint32_t _length;
  MiddlewareMessages_Waypoint *_buffer;
  bool _release;
} MiddlewareMessages_Graph_waypoints_seq;

#define MiddlewareMessages_Graph_waypoints_seq__alloc() \
((MiddlewareMessages_Graph_waypoints_seq*) dds_alloc (sizeof (MiddlewareMessages_Graph_waypoints_seq)));

#define MiddlewareMessages_Graph_waypoints_seq_allocbuf(l) \
((MiddlewareMessages_Waypoint *) dds_alloc ((l) * sizeof (MiddlewareMessages_Waypoint)))

typedef struct MiddlewareMessages_Graph_lanes_seq
{
  uint32_t _maximum;
  uint32_t _length;
  MiddlewareMessages_Lane *_buffer;
  bool _release;
} MiddlewareMessages_Graph_lanes_seq;

#define MiddlewareMessages_Graph_lanes_seq__alloc() \
((MiddlewareMessages_Graph_lanes_seq*) dds_alloc (sizeof (MiddlewareMessages_Graph_lanes_seq)));

#define MiddlewareMessages_Graph_lanes_seq_allocbuf(l) \
((MiddlewareMessages_Lane *) dds_alloc ((l) * sizeof (MiddlewareMessages_Lane)))


typedef struct MiddlewareMessages_Graph
{
  MiddlewareMessages_Graph_waypoints_seq waypoints;
  MiddlewareMessages_Graph_lanes_seq lanes;
} MiddlewareMessages_Graph;


#ifdef __cplusplus
}
#endif
#endif /* _DDSL_MIDDLEWAREMESSAGES_H_ */
