/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: MiddlewareMessages.h
  Source: MiddlewareMessages.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"

#ifndef _DDSL_MIDDLEWAREMESSAGES_H_
#define _DDSL_MIDDLEWAREMESSAGES_H_


#ifdef __cplusplus
extern "C" {
#endif


typedef struct MiddlewareMessages_Location
{
  int32_t sec;
  uint32_t nanosec;
  double x;
  double y;
  double yaw;
  char * level_name;
} MiddlewareMessages_Location;

extern const dds_topic_descriptor_t MiddlewareMessages_Location_desc;

#define MiddlewareMessages_Location__alloc() \
((MiddlewareMessages_Location*) dds_alloc (sizeof (MiddlewareMessages_Location)));

#define MiddlewareMessages_Location_free(d,o) \
dds_sample_free ((d), &MiddlewareMessages_Location_desc, (o))


typedef struct MiddlewareMessages_Waypoint
{
  uint32_t index;
  MiddlewareMessages_Location location;
} MiddlewareMessages_Waypoint;

extern const dds_topic_descriptor_t MiddlewareMessages_Waypoint_desc;

#define MiddlewareMessages_Waypoint__alloc() \
((MiddlewareMessages_Waypoint*) dds_alloc (sizeof (MiddlewareMessages_Waypoint)));

#define MiddlewareMessages_Waypoint_free(d,o) \
dds_sample_free ((d), &MiddlewareMessages_Waypoint_desc, (o))


typedef struct MiddlewareMessages_ModeParameter
{
  char * name;
  char * value;
} MiddlewareMessages_ModeParameter;

extern const dds_topic_descriptor_t MiddlewareMessages_ModeParameter_desc;

#define MiddlewareMessages_ModeParameter__alloc() \
((MiddlewareMessages_ModeParameter*) dds_alloc (sizeof (MiddlewareMessages_ModeParameter)));

#define MiddlewareMessages_ModeParameter_free(d,o) \
dds_sample_free ((d), &MiddlewareMessages_ModeParameter_desc, (o))

#define MiddlewareMessages_RobotMode_Constants_MODE_IDLE 0
#define MiddlewareMessages_RobotMode_Constants_MODE_CHARGING 1
#define MiddlewareMessages_RobotMode_Constants_MODE_MOVING 2
#define MiddlewareMessages_RobotMode_Constants_MODE_PAUSED 3
#define MiddlewareMessages_RobotMode_Constants_MODE_WAITING 4
#define MiddlewareMessages_RobotMode_Constants_MODE_EMERGENCY 5
#define MiddlewareMessages_RobotMode_Constants_MODE_GOING_HOME 6
#define MiddlewareMessages_RobotMode_Constants_MODE_DOCKING 7
#define MiddlewareMessages_RobotMode_Constants_MODE_REQUEST_ERROR 8
#define MiddlewareMessages_RobotMode_Constants_MODE_UNDEFINED 9
#define MiddlewareMessages_RobotMode_Constants_MODE_CUSTOM 10


typedef struct MiddlewareMessages_RobotMode
{
  uint32_t mode;
  char * info;
} MiddlewareMessages_RobotMode;

extern const dds_topic_descriptor_t MiddlewareMessages_RobotMode_desc;

#define MiddlewareMessages_RobotMode__alloc() \
((MiddlewareMessages_RobotMode*) dds_alloc (sizeof (MiddlewareMessages_RobotMode)));

#define MiddlewareMessages_RobotMode_free(d,o) \
dds_sample_free ((d), &MiddlewareMessages_RobotMode_desc, (o))

typedef struct MiddlewareMessages_ModeRequest_parameters_seq
{
  uint32_t _maximum;
  uint32_t _length;
  MiddlewareMessages_ModeParameter *_buffer;
  bool _release;
} MiddlewareMessages_ModeRequest_parameters_seq;

#define MiddlewareMessages_ModeRequest_parameters_seq__alloc() \
((MiddlewareMessages_ModeRequest_parameters_seq*) dds_alloc (sizeof (MiddlewareMessages_ModeRequest_parameters_seq)));

#define MiddlewareMessages_ModeRequest_parameters_seq_allocbuf(l) \
((MiddlewareMessages_ModeParameter *) dds_alloc ((l) * sizeof (MiddlewareMessages_ModeParameter)))


typedef struct MiddlewareMessages_ModeRequest
{
  char * robot_name;
  char * task_id;
  MiddlewareMessages_RobotMode mode;
  MiddlewareMessages_ModeRequest_parameters_seq parameters;
} MiddlewareMessages_ModeRequest;

extern const dds_topic_descriptor_t MiddlewareMessages_ModeRequest_desc;

#define MiddlewareMessages_ModeRequest__alloc() \
((MiddlewareMessages_ModeRequest*) dds_alloc (sizeof (MiddlewareMessages_ModeRequest)));

#define MiddlewareMessages_ModeRequest_free(d,o) \
dds_sample_free ((d), &MiddlewareMessages_ModeRequest_desc, (o))

typedef struct MiddlewareMessages_NavigationRequest_path_seq
{
  uint32_t _maximum;
  uint32_t _length;
  MiddlewareMessages_Waypoint *_buffer;
  bool _release;
} MiddlewareMessages_NavigationRequest_path_seq;

#define MiddlewareMessages_NavigationRequest_path_seq__alloc() \
((MiddlewareMessages_NavigationRequest_path_seq*) dds_alloc (sizeof (MiddlewareMessages_NavigationRequest_path_seq)));

#define MiddlewareMessages_NavigationRequest_path_seq_allocbuf(l) \
((MiddlewareMessages_Waypoint *) dds_alloc ((l) * sizeof (MiddlewareMessages_Waypoint)))


typedef struct MiddlewareMessages_NavigationRequest
{
  char * robot_name;
  char * task_id;
  MiddlewareMessages_NavigationRequest_path_seq path;
} MiddlewareMessages_NavigationRequest;

extern const dds_topic_descriptor_t MiddlewareMessages_NavigationRequest_desc;

#define MiddlewareMessages_NavigationRequest__alloc() \
((MiddlewareMessages_NavigationRequest*) dds_alloc (sizeof (MiddlewareMessages_NavigationRequest)));

#define MiddlewareMessages_NavigationRequest_free(d,o) \
dds_sample_free ((d), &MiddlewareMessages_NavigationRequest_desc, (o))


typedef struct MiddlewareMessages_RelocalizationRequest
{
  char * robot_name;
  char * task_id;
  MiddlewareMessages_Location location;
  uint32_t last_visited_index;
} MiddlewareMessages_RelocalizationRequest;

extern const dds_topic_descriptor_t MiddlewareMessages_RelocalizationRequest_desc;

#define MiddlewareMessages_RelocalizationRequest__alloc() \
((MiddlewareMessages_RelocalizationRequest*) dds_alloc (sizeof (MiddlewareMessages_RelocalizationRequest)));

#define MiddlewareMessages_RelocalizationRequest_free(d,o) \
dds_sample_free ((d), &MiddlewareMessages_RelocalizationRequest_desc, (o))

typedef struct MiddlewareMessages_RobotState_path_seq
{
  uint32_t _maximum;
  uint32_t _length;
  MiddlewareMessages_Waypoint *_buffer;
  bool _release;
} MiddlewareMessages_RobotState_path_seq;

#define MiddlewareMessages_RobotState_path_seq__alloc() \
((MiddlewareMessages_RobotState_path_seq*) dds_alloc (sizeof (MiddlewareMessages_RobotState_path_seq)));

#define MiddlewareMessages_RobotState_path_seq_allocbuf(l) \
((MiddlewareMessages_Waypoint *) dds_alloc ((l) * sizeof (MiddlewareMessages_Waypoint)))


typedef struct MiddlewareMessages_RobotState
{
  char * name;
  char * model;
  char * task_id;
  MiddlewareMessages_RobotMode mode;
  double battery_percent;
  MiddlewareMessages_Location location;
  MiddlewareMessages_RobotState_path_seq path;
} MiddlewareMessages_RobotState;

extern const dds_topic_descriptor_t MiddlewareMessages_RobotState_desc;

#define MiddlewareMessages_RobotState__alloc() \
((MiddlewareMessages_RobotState*) dds_alloc (sizeof (MiddlewareMessages_RobotState)));

#define MiddlewareMessages_RobotState_free(d,o) \
dds_sample_free ((d), &MiddlewareMessages_RobotState_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_MIDDLEWAREMESSAGES_H_ */
