/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: MiddlewareMessages.c
  Source: MiddlewareMessages.idl
  Cyclone DDS: V0.7.0

*****************************************************************/
#include "MiddlewareMessages.h"











