module MiddlewareMessages
{
  struct Location
  {
    long sec;
    unsigned long nanosec;
    double x;
    double y;
    double yaw;
    string level_name;
  };
  struct ModeParameter
  {
    string name;
    string value;
  };
  module RobotMode_Constants
  {
    const unsigned long MODE_IDLE = 0;
    const unsigned long MODE_CHARGING = 1;
    const unsigned long MODE_MOVING = 2;
    const unsigned long MODE_PAUSED = 3;
    const unsigned long MODE_WAITING = 4;
    const unsigned long MODE_EMERGENCY = 5;
    const unsigned long MODE_GOING_HOME = 6;
    const unsigned long MODE_DOCKING = 7;
    const unsigned long MODE_REQUEST_ERROR = 8;
    const unsigned long MODE_UNDEFINED = 9;
    const unsigned long MODE_CUSTOM = 10;  
  };
  struct RobotMode
  {
    unsigned long mode;
    string info;
  };
  struct ModeRequest
  {
    string robot_name;
    string task_id;
    RobotMode mode;
    sequence<ModeParameter> parameters;
  };
  struct NavigationRequest
  {
    string robot_name;
    string task_id;
    sequence<Location> path;
  };
  struct RobotState
  {
    string name;
    string model;
    string task_id;
    RobotMode mode;
    double battery_percent;
    Location location;
    sequence<Location> path;
  };
  struct GraphRequest
  {
    unsigned long version;
  };
  struct Waypoint
  {
    string map_name;
    double x;
    double y;
    boolean is_holding_point;
    boolean is_passthrough_point;
    boolean is_parking_spot;
    unsigned long index;
    string name;
  };
  struct Lane
  {
    unsigned long entry;
    unsigned long exit;
  };
  struct Graph
  {
    sequence<Waypoint> waypoints;
    sequence<Lane> lanes;
  };
};
