name: integration-tests

on: push

jobs:
  integration-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:${{ matrix.ros_distribution }}-desktop-noble
    strategy:
      matrix:
        ros_distribution:
          - jazzy

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start test fixture containers
        run: docker-compose -f ".github/docker/integration-tests/docker-compose.yaml" up -d --build

      - name: build-and-test
        uses: ./.github/actions/build-and-test
        with:
          ros-distribution: ${{ matrix.ros_distribution }}
          zenoh-version: 1.0.1
          integration-testing: ON

      - name: Stop test fixture containers
        if: always()
        run: docker-compose -f ".github/docker/integration-tests/docker-compose.yaml" down
