name: nav2-integration-tests

on: push
defaults:
  run:
    shell: bash

jobs:
  integration-tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:${{ matrix.ros_distribution }}-desktop
    strategy:
      matrix:
        ros_distribution:
          - jazzy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Install docker-compose
        run: |
          apt update
          apt install docker-compose -y

      - name: Start test fixture containers
        run: docker-compose -f ".github/docker/integration-tests/nav2-docker-compose.yaml" up -d --build

      - name: build-and-test
        uses: ./.github/actions/build-and-test
        with:
          ros-distribution: ${{ matrix.ros_distribution }}
          zenoh-version: 1.1.0
          nav2-integration-testing: ON

      - name: Stop test fixture containers
        if: always()
        run: docker-compose -f ".github/docker/integration-tests/nav2-docker-compose.yaml" down

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ros_ws/coveragepy/.coverage
          flags: tests
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
