name: nav2-e2e-tests

on: push
defaults:
  run:
    shell: bash

jobs:
  e2e-tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:${{ matrix.ros_distribution }}-desktop
    strategy:
      matrix:
        ros_distribution:
          - jazzy
          # - rolling

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Install docker-compose
        run: |
          apt update
          apt install docker-compose -y

      - name: Start test fixture containers
        run: docker-compose -f ".github/docker/integration-tests/nav2-docker-compose.yaml" up -d --build

      - name: Setup
        run: |
          apt update
          apt install -y ros-${{ matrix.ros_distribution }}-rmw-cyclonedds-cpp python3-pip
          pip3 install nudged eclipse-zenoh==1.1.0 pycdr2 rosbags --break-system-packages
          colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          colcon mixin update default
          rosdep update
          rosdep install --from-paths . -yir

      - name: Build
        run: /ros_entrypoint.sh colcon build --packages-up-to free_fleet_examples --event-handlers=console_cohesion+ --mixin release --cmake-args -DNAV2_INTEGRATION_TESTING=ON

      - name: Tests
        env:
          RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
          ROS_DOMAIN_ID: 0
        run: . ./install/setup.bash && cd free_fleet_examples/tests/e2e/ && python3 -m unittest

      - name: Stop test fixture containers
        if: always()
        run: docker-compose -f ".github/docker/integration-tests/nav2-docker-compose.yaml" down
