# From https://medium.com/@aarne.laur/retry-failed-github-actions-8661e7601c66
name: Retry workflow

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: string, ID of the github workflow run
        required: true
jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - name: rerun ${{ inputs.run_id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run watch ${{ inputs.run_id }} > /dev/null 2>&1
          gh run rerun ${{ inputs.run_id }} --failed
